### PR TITLE
Make bigwig work with R16 + latest version of cowboy

### PR DESCRIPTION
**Pull request by ldx**
This is mainly a refactoring of bigwig to make sure it can run on a recent Erlang/OTP release and works with the latest version of cowboy.

### CODE REVIEW

**Comment by gonzaloserrano** [comment]
Works in R16B03 :+1:

**Comment by ruanhao** [comment]
good

**Comment by marcosQuesada** [comment]
:+1:

**Comment by jwilberding** [comment]
Sorry, this was an accident, meant to merge into my own fork.

**Pull request closed without merging**
